storeFile=/root/array-operator/apps/owner-web/store/signing/array-operator-release.jks
storePassword=69434e247090ddaa760437f0949e037f
keyAlias=arrayoperator
keyPassword=69434e247090ddaa760437f0949e037f
